server:
  port: 9090
spring:
  application:
    name: ticketing-project-rest
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/Cybertek_Rest_Security_DB
    username: postgres
    password: 1127
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    data: classpath:data.sql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: false
security:
  jwt:
    secret-key: cybertek
springdoc:
  swagger-ui:
    path: /swagger-ui.html